name: yolo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.25.1
  - scipy=1.11.3
  - pip
  - pip:
      - supervision==0.23.0
      - opencv-python==4.10.0.84
      - opencv-contrib-python==4.10.0.84
      - ultralytics==8.3.221
      - ultralytics-thop==2.0.17
